version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: nest
    networks:
      - db
      - backend 
      - frontend
      - server

    ports:
      - 3000:5000

    command: npm run start:dev

  db:
    build:
      context: ./db
      dockerfile: Dockerfile

    container_name: mysql
    restart: always

    volumes:
      - mysql:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=items

    networks:
      - db
      - backend

  frontend:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile

    networks:
      - backend
      - frontend

    ports:
      - 9000:8000

    depends_on:
      - backend

    command: npm run dev

volumes:
  mysql:
  f_src:
  f_node_modules:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  db:
    driver: bridge
  server:
    driver: bridge

