version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    working_dir: /nest

    volumes:
      - ./backend/dist/:/nest/dist
      - ./backend/node_modules/:/nest/node_modules
    
    container_name: nest
    # Lautaro del futuro, NO TOQUES ESTO
    # Para que dos contenedores se intercambien información en necesario que AMBÓS tengan ls red
    networks:
      - db
      - backend # <-- SI O SI este debe conincidir con la base de datos o cualquier contenedor que se conecte al backend
      - frontend
      - server

    ports:
      - 3000:5000

    environment:
      - NEST_APP_PORT=5000
    
    command: node dist/main.js

  db:
    build:
      context: ./db
      dockerfile: Dockerfile

    container_name: mysql
    restart: always

    volumes:
      - mysql:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=items

    networks:
      - db
      - backend

  nginx:
    image: "nginx:1.25.3-alpine"
    container_name: "server"
    
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "8080:80"

    environment:
      - NGINX_HOST=lauta.com
      - NGINX_PORT=80
      - NODE_PATH=/node_modules

    networks:
      - backend # <-- SI O SI este debe conincidir con la base de datos o cualquier contenedor que se conecte al backend
      - server

volumes:
  mysql:
  f_src:
  f_node_modules:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  db:
    driver: bridge
  server:
    driver: bridge

